[Categories]

 #Edit this file as you want, is's a precompiled list if you want to generate a file with the selected categories below, in the code there's an option for only 1 categories or multiple categories, but if you want to use this file as a reference for repetitive taks, you can use it and remove the comment sign before the caregory name

 #214 = Code Execution

 #215 = Copy Left

 #213 = Prohibited Suppliers

 #148 = Application

 #47 = Academic Fraud

 161 = Adult

 40 = Adult Themes

 27 = Advertisements

 #0 = Adware

 #1 = Alcohol

 #196 = Animals and Pets

 #57 = Anime/Manga/Webcomic

 #111 = Arts

 #112 = Astrology

 #2 = Auctions

 #48 = Automotive

 #3 = Blogs

 #32 = Business Services

 #163 = Business and Industry

 #197 = Cannabis

 #4 = Chat

 #164 = Chat and Instant Messaging

 #165 = Cheating and Plagiarism

 #166 = Child Abuse Content

 #5 = Classifieds

 #198 = Cloud and Data Centers

 #113 = Computer Security

 #167 = Computers and Internet

 #199 = Conventions, Conferences and Trade Shows

 #200 = Cryptocurrency

 #145 = DIY Projects

 #6 = Dating

 #114 = Digital Postcards

 #115 = Dining and Drinking

 #7 = Drugs

 #116 = Dynamic and Residential

 #8 = Ecommerce/Shopping

 #168 = Education

 #33 = Educational Institutions

 #201 = Encrypted DNS

 #169 = Entertainment

 #170 = Extreme

 #117 = Fashion

 #9 = File Storage

 118 = File Transfer Services

 #171 = Filter Avoidance

 #172 = Finance

 #34 = Financial Institutions

 #49 = Forums/Message boards

 #119 = Freeware and Shareware

 #10 = Gambling

 #11 = Games

 #212 = Generative AI

 #56 = German Youth Protection

 #35 = Government

 #173 = Government and Law

 #120 = Hacking

 #174 = Hate Speech

 #12 = Hate/Discrimination

 #13 = Health and Fitness

 #175 = Health and Medicine

 #14 = Humor

 #146 = Hunting

 #157 = IT-ADM

 #156 = IT-AGCOM

 #121 = Illegal Activities

 122 = Illegal Downloads

 #176 = Illegal Drugs

 #123 = Infrastructure and Content Delivery Networks

 #15 = Instant Messaging

 #124 = Internet Telephony

 #85 = Internet Watch Foundation

 #202 = Internet of Things

 #177 = Job Search

 #16 = Jobs/Employment

 #178 = Lingerie and Swimsuits

 #41 = Lingerie/Bikini

 #125 = Lotteries

 #147 = Military

 #126 = Mobile Phones

 #17 = Movies

 #203 = Museums

 #36 = Music

 #127 = Nature and Conservation

 #179 = News

 #18 = News/Media

 #50 = Non-Profits

 #180 = Non-governmental Organizations

 #181 = Non-sexual Nudity

 #182 = Not Actionable

 #42 = Nudity

 #183 = Online Communities

 #205 = Online Document Sharing and Collaboration

 #142 = Online Meetings

 184 = Online Storage and Backup

 #128 = Online Trading

 #141 = Organizational Email

 #19 = P2P/File sharing

 #143 = Paranormal

 #37 = Parked Domains

 #186 = Peer File Transfer

 #129 = Personal Sites

 144 = Personal VPN

 #187 = Photo Search and Images

 #20 = Photo Sharing

 #51 = Podcasts

 #52 = Politics

 #44 = Pornography

 #21 = Portals

 #206 = Private IP Addresses as Host

 #130 = Professional Networking

 #43 = Proxy/Anonymizer

 #22 = Radio

 #131 = Real Estate

 #207 = Recipes and Food

 #188 = Reference

 #208 = Regional Restricted Sites (Germany)

 #209 = Regional Restricted Sites (Great Britain)

 #210 = Regional Restricted Sites (Italy)

 #211 = Regional Restricted Sites (Poland)

 #189 = Religion

 #53 = Religious

 #54 = Research/Reference

 #132 = SaaS and B2B

 #133 = Safe for Kids

 #134 = Science and Technology

 #23 = Search Engines

 #190 = Search Engines and Portals

 135 = Sex Education

 45 = Sexuality

 #191 = Shopping

 #24 = Social Networking

 #136 = Social Science

 #137 = Society and Culture

 #138 = Software Updates

 #25 = Software/Technology

 #39 = Sports

 #192 = Sports and Recreation

 #193 = Streaming Audio

 #194 = Streaming Video

 #46 = Tasteless

 #26 = Television

 #149 = Terrorism

 #204 = Terrorism and Violent Extremism

 #38 = Tobacco

 #195 = Transportation

 #55 = Travel

 107 = URL Shorteners

 #28 = Video Sharing

 #29 = Visual Search Engines

 #30 = Weapons

 #185 = Web Cache and Archives

 139 = Web Hosting

 #140 = Web Page Translation

 #58 = Web Spam

 #162 = Web-based Email

 #31 = Webmail

 #72 = Allow List

 #152 = Application Allow

 #151 = Application Block

 #159 = Application Warn

 #71 = Block List

 #65 = Command and Control

 #64 = Command and Control

 #150 = Cryptomining

 #110 = DNS Tunneling VPN

 #60 = Drive-by Downloads/Exploits

 #61 = Dynamic DNS

 #63 = High Risk Sites and Locations

 #66 = Malware

 #67 = Malware

 #62 = Mobile Threats

 #108 = Newly Seen Domains

 #68 = Phishing

 #109 = Potentially Harmful

 #106 = Unauthorized IP Tunnel Access

 #73 = Global Whitelist

 #153 = Infringing Intellectual Property

 #74 = Sinkhole
